# Generated by Django 2.2 on 2019-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='user_vote',
            field=models.BooleanField(default=False),
        ),
    ]
