# Generated by Django 2.2 on 2019-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_discovery_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='embed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
